### ISSUE TITLE
Add support for Cobalt

### ISSUE THREAD

**Issue by putsi** [avlidienbrunn/bountydash#1]
Very nice tool👍🥇!

I noticed that there is no support for Cobalt which is one of the major bounty platforms.
Thus this issue is for implementing such support. 
I might do a pull request for this if I can manage some time.

**Comment by fransr** [comment]
I've finalized a working concept for Cobalt https://github.com/avlidienbrunn/bountydash/commit/b61030bd01993342ddb70e31b46719f856c245b3. Could you try and see if it looks good on your side? If so, I'll update the Support-part in the README explaining we support Cobalt.

**Comment by fransr** [comment]
Closing this one as done due to: https://github.com/avlidienbrunn/bountydash/commit/b61030bd01993342ddb70e31b46719f856c245b3#diff-c77196bcda946616edcc5048fbece15e
please try it out and file a bug report if you have any issues :)
