### ISSUE TITLE
Add support for Google VRP

### ISSUE THREAD

**Issue by CSVi** [avlidienbrunn/bountydash#2]
Awesome tool guys 👍 I see that there is currently no support for the Google VRP, would be pretty neat if this could be added.

**Comment by fransr** [comment]
I've made an attempt at doing this, could you try it out? https://github.com/avlidienbrunn/bountydash/commit/630339196d599a6da6236d2efcd65d16b4c6e1a7

Basically what I want to find out is if it catches all scenarios of items from the Dashboard in Bughunter. In my list it looks like it catches the ones I got paid for, which are the ones we want.

Please let me know how it goes and I'll update the readme with support for Google.

**Comment by fransr** [comment]
@avlidienbrunn made some fixes for it, please try the latest one.

**Comment by fransr** [comment]
I'm closing this issue as completed now due to https://github.com/avlidienbrunn/bountydash/commit/8ccc91053a912af713e42c250492be5187626941 which should fix most of the edge cases in the VRP-list

**Comment by CSVi** [comment]
Just tried this out, works great! Thank you 👍
